name: 'Minikube setup action'
description: 'Sets up minikube on the github runner'

runs:
  using: "composite"
  steps:
    - name: Free up disk space
      run: |
        # https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
        # du -sh /*        2> /dev/null | sort -rh  2> /dev/null | head
        # du -h -d2 /usr   2> /dev/null | sort -rh  2> /dev/null | head
        echo "Check free disk space before cleanup."
        df -h
        echo "Removing non-essential tools and libraries."
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/share/boost
        # delete libraries for Android (12G), PowerShell (1.3G), Swift (1.7G)
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/share/swift
        echo "Check free disk space after cleanup."
        df -h
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.26.0'
    - name: Setup Minikube
      uses: medyagh/setup-minikube@latest
      with:
        minikube-version: '1.28.0'
        kubernetes-version: 'v1.26.4'
        driver: 'none'
        wait: 'all'
        start-args: --wait-timeout=120s
    - name: Check Kubernetes pods
      shell: bash
      run: kubectl get pods -n kube-system
    - name: Setup KServe dependencies
      shell: bash
      run: |
        ./test/scripts/gh-actions/setup-deps.sh

        kubectl get pods -n istio-system
        kubectl describe svc -n istio-system istio-ingressgateway
        kubectl get pods -n knative-serving
        kubectl get pods -n cert-manager
    
    - name: Update test overlays
      shell: bash
      run: |
        ./test/scripts/gh-actions/update-test-overlays.sh
        docker image ls
        cat ./config/overlays/test/configmap/inferenceservice.yaml

    - name: Prune docker images
      run: |
        echo "Pruning docker images"
        docker image prune -a -f
        docker system df
        df -h
