name: 'Minikube setup action'
description: 'Sets up minikube on the github runner'

runs:
  using: "composite"
  steps:
    - name: Free up disk space
      shell: bash
      run: |
        echo "Disk usage before cleanup:"
        df -h

        # remove non-essential tools and libraries, see:
        # https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/share/boost

        # delete libraries for Android (12G), CodeQL (5.3G), PowerShell (1.3G), Swift (1.7G)
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf "${AGENT_TOOLSDIRECTORY}/CodeQL"
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/share/swift

        echo "Disk usage after cleanup:"
        df -h

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.26.0'

    - name: Setup Minikube
      uses: medyagh/setup-minikube@latest
      with:
        minikube-version: '1.28.0'
        kubernetes-version: 'v1.26.4'
        driver: 'none'
        wait: 'all'
        start-args: --wait-timeout=120s

    - name: Check Kubernetes pods
      shell: bash
      run: kubectl get pods -n kube-system

    - name: Prune docker images
      shell: bash
      run: |
        echo "Pruning docker images"
        docker image prune -a -f
        docker system df
        df -h
